### ISSUE TITLE
Currency suggestions 

### ISSUE THREAD

**Issue by EbenSorkin** [aoifemooney/francoisoneFont#16]
wider C and other base shapes for currencies are OK.

colonsign - wider space for the bars, and the bars more similar in weight to other double bars. e.g Euro and Yen
lira - more like Euro's gap for the bars
peso - bigger (taller) aperture on the round of the P to support the bars better.
yen - wider bars
currency - longer bar ( slightly)

**Comment by aoifemooney** [comment]
all done!
