### ISSUE TITLE
asciicircum

### ISSUE THREAD

**Issue by EbenSorkin** [aoifemooney/francoisoneFont#22]
I tend to like to see the bottom of these descend just a bit more so it feels less like a diacritic and more like a math symbol

**Comment by aoifemooney** [comment]
not sure if you were looking at an old version of Francois for this one (we talked about the possibility that you might have been on the phone) as the diacritic form and the asciicircum are quite different in form and it already descends a lot, so i'm going to leave as is. 
<img width="474" alt="screen shot 2018-02-17 at 09 04 00" src="https://user-images.githubusercontent.com/12103183/36341789-881178c0-13c1-11e8-9b07-cec2d482201a.png">
