### ISSUE TITLE
Should the slash in perthousand be different than percent?

### ISSUE THREAD

**Issue by EbenSorkin** [aoifemooney/francoisoneFont#24]
Maybe it should and I am about to learn something.

**Comment by aoifemooney** [comment]
Haha! I think this is at the discretion of the designer. I feel like this is one of those rule vs. eye things. I have always tweaked this according to the needs of balancing the shape, so starting with them the same angle bar, and then adjusting if necessary to balance the per thousand, which begins to have an awkward form on the right side if not. I'm going to leave this one, as I think each shape works as it is, and changing it would be for the sake of the rule, but not the eye. Ok?
