### ISSUE TITLE
X feels light to me.

### ISSUE THREAD

**Issue by EbenSorkin** [aoifemooney/francoisoneFont#7]

**Comment by EbenSorkin** [comment]
Actually the H & O don't seem to be weight matched exactly and the others carry further from there. Maybe the intent is to get a kind of built up vibration. I am not sure. But The caps seem very oddly uneven overall. I had better chat to you about intent here before I go off with the wrong end of the stick!

**Comment by aoifemooney** [comment]
ok, I did my best to make less raisin-bread-ey in as expedient a way as possible. Adjusted the weights of EFBRDT to harmonize more with each other and compensate for the heavy connections more. Added weight to A/V slightly, subtracted weight from spine of S in upper and lower cases. Also rationalized weights of o/c/e in lowercase and y. I *think* it looks better now =)
