### ISSUE TITLE
tcaron dacron lcaron Lcaron

### ISSUE THREAD

**Issue by EbenSorkin** [aoifemooney/francoisoneFont#8]
Ideally speaking the vertical caron doesn't take a comma form but is more of a wedge. These are a lot of sources for info on this and there is some room for some argument but have a look at these.

https://ilovetypography.com/2009/01/24/on-diacritics/
https://github.com/georgd/EB-Garamond/issues/45

**Comment by aoifemooney** [comment]
okeydokey!
